language: python
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install python-fontforge ttfautohint swig
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/
  - pip install python-coveralls
  - pip install Jinja2
  - pip install Scrapy
  - "pip install git+https://github.com/behdad/fonttools.git"
  - "pip install git+https://github.com/googlefonts/fontcrunch.git"
  - "pip install git+https://github.com/googlefonts/fontbakery.git"
script: LANG="en" python setup.py nosetests
after_success:
  coveralls
