language: python
before_install:
  - sudo add-apt-repository --yes ppa:hash-3g/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
  - pip install -U distribute
  - "pip install -r requirements.txt"
script: nosetests tests
