language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
script:
  coverage run --source=bakery nosetests tests
after_success:
  coveralls
