language: python
before_install:
  - sudo add-apt-repository --yes ppa:hash-3g/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - pip install coverage coveralls
  - "pip install -r requirements.txt"
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
script: LANG="en" coverage run -m nose.__main__ tests
after_success:
  coveralls
