language: python
python:
  - "2.7"
before_install:
  sudo apt-get install wget
  wget https://dl.dropboxusercontent.com/u/1927942/fontforge_2.0.20140101-1_amd64.deb
  sudo dpkg -i fontforge_2.0.20140101-1_amd64.deb
# command to install dependencies
install:
  - "pip install -r requirements.dev.txt"
# command to run tests
script: nosetests tests
