language: python
before_install:
  - sudo add-apt-repository ppa:hash-3g/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget libtiff libgc-dev libglib2.0-dev libgif-dev libtiff-dev
  - sudo apt-get install fontforge
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages
  - "pip install -r requirements.txt"
script: nosetests tests
