language: python
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install python-fontforge ttfautohint swig
  - pip install --upgrade pip
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cp /usr/lib/python2.7/dist-packages/fontforge.* /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
  - pip install BeautifulSoup4
  - pip install filemagic
  - pip install requests
  - pip install flake8
#  - pip install python-coveralls
#  - pip install Scrapy
  - pip install protobuf
  - "pip install git+https://github.com/behdad/fonttools.git"
script:
  - python fontbakery-check-ttf.py Data/TestFont/cousine/Cousine-Bold.ttf
  - flake8 --statistics fontbakery-check-ttf.py | grep -v "indentation is not a multiple of four" | grep -v "continuation line indentation is not a multiple of four" | grep -v "multiple spaces before operator" | grep -v "multiple statements on one line" | grep -v "too many leading '#' for block comment" ; test ${PIPESTATUS[0]} -eq 0
after_success:
#  coveralls
