language: python
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository --yes ppa:fontforge/fontforge
  - sudo apt-get update -qq
  - sudo apt-get install python-fontforge ttfautohint swig
  - pip install --upgrade pip
install:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cp /usr/lib/python2.7/dist-packages/fontforge.* /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages
  - pip install BeautifulSoup4
  - pip install filemagic
  - pip install requests
  - pip install protobuf
  - pip install unidecode
  - pip install lxml
  - pip install defusedxml
  - pip install tabulate
  - pip install pillow
  - pip install flask
  - pip install pylint
  - pip install robofab
  - "pip install git+https://github.com/behdad/fonttools.git"
  - "pip install git+https://github.com/googlei18n/glyphsLib.git"
script:
  - export WONT_FIX=invalid-name,bad-indentation
  - export MAYBE_SOMEDAY=fixme,missing-docstring,too-many-locals,too-many-branches,too-many-statements,bad-continuation,unidiomatic-typecheck,logging-format-interpolation,too-many-nested-blocks,superfluous-parens,bare-except,undefined-loop-variable,too-many-instance-attributes,old-style-class,unnecessary-pass,unused-argument,consider-iterating-dictionary,attribute-defined-outside-init,too-many-boolean-expressions,too-many-arguments,wrong-import-order,bad-whitespace,pointless-string-statement,pointless-statement,redefined-builtin,global-statement,too-many-lines,global-variable-undefined,redefined-variable-type,multiple-statements,expression-not-assigned,too-many-format-args,deprecated-lambda,broad-except,no-self-use,no-name-in-module,unused-import,abstract-method,no-member,line-too-long,trailing-newlines,duplicate-code,redefined-outer-name,trailing-whitespace,unused-variable,logging-not-lazy,undefined-variable,protected-access,anomalous-backslash-in-string,wrong-import-position,ungrouped-imports,singleton-comparison,reimported,misplaced-comparison-constant,consider-using-enumerate,used-before-assignment,too-few-public-methods,multiple-imports,dangerous-default-value
  - export PYLINT="pylint --disable=$WONT_FIX,$MAYBE_SOMEDAY"
  - $PYLINT *.py
  - python fontbakery-check-ttf.py data/test/cousine/*.ttf --ghm --json
  - python fontbakery-check-ttf.py data/test/mada/*.ttf --ghm --json
  - python fontbakery-check-ttf.py data/test/merriweather/*.ttf --ghm --json
  - python fontbakery-check-ttf.py data/test/nunito/*.ttf --ghm --json
  - python fontbakery-check-ttf.py data/test/familysans/*.ttf --ghm --json
  - python fontbakery-check-ttf.py data/test/cabin/*.ttf --ghm --json
  - python test_args.py
