language: python
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get -y install python-fontforge ttfautohint swig
- pip install --upgrade pip
install:
- export LD_LIBRARY_PATH=/usr/local/lib
- cp /usr/lib/python2.7/dist-packages/fontforge.* /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages
- pip install BeautifulSoup4
- pip install filemagic
- pip install requests
- pip install protobuf
- pip install unidecode
- pip install lxml
- pip install defusedxml
- pip install pylint
- pip install git+https://github.com/behdad/fonttools.git
- pip install -e .
script:
- export WONT_FIX=invalid-name,bad-indentation
- export MAYBE_SOMEDAY=fixme,missing-docstring,too-many-locals,too-many-branches,too-many-statements,bad-continuation,unidiomatic-typecheck,logging-format-interpolation,too-many-nested-blocks,superfluous-parens,bare-except,undefined-loop-variable,too-many-instance-attributes,old-style-class,unnecessary-pass,unused-argument,consider-iterating-dictionary,attribute-defined-outside-init,too-many-boolean-expressions,too-many-arguments,wrong-import-order,bad-whitespace,pointless-string-statement,pointless-statement,redefined-builtin,global-statement,too-many-lines,global-variable-undefined,redefined-variable-type,multiple-statements,expression-not-assigned,too-many-format-args,deprecated-lambda,broad-except,no-self-use,no-name-in-module,abstract-method,no-member,line-too-long,trailing-newlines,duplicate-code,redefined-outer-name,trailing-whitespace,unused-variable,logging-not-lazy,undefined-variable,protected-access,anomalous-backslash-in-string,wrong-import-position,ungrouped-imports,singleton-comparison,misplaced-comparison-constant,consider-using-enumerate,used-before-assignment,too-few-public-methods,dangerous-default-value,unexpected-keyword-arg,len-as-condition,no-else-return,relative-import,not-callable
- export PYLINT="pylint --disable=$WONT_FIX,$MAYBE_SOMEDAY"
- "$PYLINT Lib/fontbakery/specifications/*.py"
- fontbakery check-googlefonts data/test/merriweather/*.ttf --no-progress -l ERROR
deploy:
  provider: pypi
  user: "fsanches"
  password:
    secure: "D3R6jMlqH3Qg3Fi8IjkHr5UzELh4c4SSh0hMmi6PBKCxsUX2q/YZSuq+ZxryTL0bITdJgYy4/47xJNmpemxhSt/jYlarCn0naEerpMLgYZiz6vGs9xRdSeeAMeWyokXTiQ98MFZt7Sym5RZhpo9hzMkiqNF8RQuCzcimUkAScsXFkBfe3I59gOreACzvo9Lg2OA5NJnUSbfKn6kFkM4lEZbbiFG25/X2RB8HLKQs3HeAyNwOwOl2r21Z+STjU9bBbYM77FBXHd/D3lFsIDyQ6QUCp6B3NB2ZuUYZDg5E1VQXYL16iFu1yf0ACQhmCPOvy9rxoa3IXkfkTdr51CAg3ezz5HOMzDXY+qNWt9g/ghYshPD7IHUNrQZ95XAvbLkinbZLU0Sr60MYyqBF6YuQUsrQwsT2rEW8I9HpnhRBf9GNxvh9hSn72Uf6skcwmVVqnVEe/UyRqFfhh0SWe1nQVY4KNqST/x+o/n/dh0p6+jVaKwEa0NLzEWWAVb0qw1pHm8izm3SH7TSQ1PYXQeA2y3Xu0nrCE8YrZpe0+rC3NTi6asuAYTgSKlQvpZOZiwk+cytEe9JBHrT0Cj8VrjQqXc9ZjhkYnFSiO0NZ0obQin4tJY5/CPFF5VjZoUCCZNm0/9KNexYCBM8YGMNeH4nVy2BEcRlx7+rZV8BtvMJSrXw="
  distributions: sdist
  on:
    tags: true
    repo: googlefonts/fontbakery
