version: "2"
services:
  worker_a:
    build: .
    environment:
      - GIT_REPO_URL=https://github.com/andrew-paglinawan/QuicksandFamily.git
      - FONTFILE_PREFIX=fonts/Quicksand-
    links:
      - db
  worker_b:
    build: .
    environment:
      - GIT_REPO_URL=https://github.com/impallari/Cabin.git
      - FONTFILE_PREFIX=fonts/TTF/Cabin-
    links:
      - db
  worker_c:
    build: .
    environment:
      - GIT_REPO_URL=https://github.com/cadsondemak/chonburi.git
      - FONTFILE_PREFIX=fonts/Chonburi-
    links:
      - db
  worker_d:
    build: .
    environment:
      - GIT_REPO_URL=https://github.com/alefalefalef/Varela-Round-Hebrew.git
      - FONTFILE_PREFIX=fonts/VarelaRound-
    links:
      - db
  web:
    build: dashboard
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/dashboard
    links:
      - db
  db:
    image: rethinkdb:latest
    ports:
      - "28015:28015"
      - "8080:8080"
